import { useState } from "react";

import Head from "next/head";
import Image from "next/image";

import TextButton from "./TextButton";
import IconButton from "./IconButton";

import { auth, db } from "../firebase";
import { signOut } from "firebase/auth";
import {
  doc,
  updateDoc,
  arrayUnion,
  query,
  collection,
  where,
  getDocs,
} from "firebase/firestore";
import { useCollection } from "react-firebase-hooks/firestore";

import {
  ArrowRightOnRectangleIcon,
  MagnifyingGlassIcon,
} from "@heroicons/react/24/outline";
import CustonInput from "./CustonInput";
import Avatar from "./Avatar";

function Chat({ user }) {
  const [searchInput, setSearchInput] = useState("");
  const [contacts, loading, error] = useCollection(
    query(
      collection(db, "users"),
      where("contacts", "array-contains", user.email)
    )
  );

  // if (snapshot) {
  //   snapshot.docs.forEach((doc) => {
  //     console.log(doc.data());
  //   });
  // }

  const startConversation = async () => {
    await updateDoc(doc(db, "users", user.email), {
      contacts: arrayUnion(searchInput),
    });

    await updateDoc(doc(db, "users", searchInput), {
      contacts: arrayUnion(user.email),
    });
  };

  return (
    <div>
      <Head>
        <title>hypercomms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-full space-x-4 overflow-hidden flex p-4 ">
        {/* Left */}
        <div className="w-1/4 rounded-xl">
          {/* Control Panel */}
          <div className="bg-gray-50 rounded-xl p-4 flex items-center justify-between">
            <Avatar src={user?.photoURL} />
            <IconButton
              Icon={ArrowRightOnRectangleIcon}
              onClick={() => {
                signOut(auth);
              }}
            />
          </div>
          {/* Search Panel */}
          <div>
            <CustonInput
              Icon={MagnifyingGlassIcon}
              placeholder={"Search"}
              value={searchInput}
              setValue={setSearchInput}
            />

            <TextButton
              text="Start conversation"
              className={"text-sm w-full rounded-t-none bg-pink-500"}
              onClick={startConversation}
            />
          </div>
          {/* Contacts Panel */}
          <div className="mt-4">
            {contacts?.docs.map((contact) => (
              <div className="flex p-4 bg-gray-50 rounded-xl items-center cursor-pointer hover:brightness-95 duration-75 ease-in-out active:brightness-90">
                <Avatar src={contact.data().photoURL} />
                <div className="flex flex-col flex-1 items-start ml-4">
                  <p className="text-sm">{contact.data().displayName}</p>
                  <p className="text-xs opacity-50">Hey!</p>
                </div>
                <p className="text-xs opacity-50">5m ago</p>
              </div>
            ))}
          </div>
        </div>
        {/* Right */}
        <div className="w-3/4 bg-gray-50 rounded-xl"></div>
      </div>
    </div>
  );
}

export default Chat;
